[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

# متغيرات البيئة يجب تعيينها من خلال واجهة Railway
# وليس هنا في ملف railway.toml 