[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[environments]
PORT = 8501 